version: '3.9'
services:
  xyz-forge-api:
    image: xyz-forge-api
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    ports:
      - "8080:8080"
    env_file:
      - ./XYZ-Forge-API/.env