version: '3.9'
services:
  xyz-forge-api:
    image: xyz-forge-api
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY="g93KsFp02+3BtpxgLM92sGytv4N32FbkXaPbG8TnxUs="
      - MONGODB_CONNECTION_STRING=mongodb+srv://xyzforgeapi:zDXd2HTZSCEGVliG@xyz-forge-api.eswbw.mongodb.net/?retryWrites=true&w=majority&appName=XYZ-Forge-API
      - MONGODB_DATABASE_NAME=XYZ-Forge-API
